<?xml version="1.0" encoding="ASCII"?>

<!-- oks-schema version 2.2 -->


<!DOCTYPE oks-schema [
  <!ELEMENT oks-schema (info, (include)?, (comments)?, (class)+)>
  <!ELEMENT info EMPTY>
  <!ATTLIST info
      name CDATA #IMPLIED
      type CDATA #IMPLIED
      num-of-items CDATA #REQUIRED
      oks-format CDATA #FIXED "schema"
      oks-version CDATA #REQUIRED
      created-by CDATA #IMPLIED
      created-on CDATA #IMPLIED
      creation-time CDATA #IMPLIED
      last-modified-by CDATA #IMPLIED
      last-modified-on CDATA #IMPLIED
      last-modification-time CDATA #IMPLIED
  >
  <!ELEMENT include (file)+>
  <!ELEMENT file EMPTY>
  <!ATTLIST file
      path CDATA #REQUIRED
  >
  <!ELEMENT comments (comment)+>
  <!ELEMENT comment EMPTY>
  <!ATTLIST comment
      creation-time CDATA #REQUIRED
      created-by CDATA #REQUIRED
      created-on CDATA #REQUIRED
      author CDATA #REQUIRED
      text CDATA #REQUIRED
  >
  <!ELEMENT class (superclass | attribute | relationship | method)*>
  <!ATTLIST class
      name CDATA #REQUIRED
      description CDATA ""
      is-abstract (yes|no) "no"
  >
  <!ELEMENT superclass EMPTY>
  <!ATTLIST superclass name CDATA #REQUIRED>
  <!ELEMENT attribute EMPTY>
  <!ATTLIST attribute
      name CDATA #REQUIRED
      description CDATA ""
      type (bool|s8|u8|s16|u16|s32|u32|s64|u64|float|double|date|time|string|uid|enum|class) #REQUIRED
      range CDATA ""
      format (dec|hex|oct) "dec"
      is-multi-value (yes|no) "no"
      init-value CDATA ""
      is-not-null (yes|no) "no"
      ordered (yes|no) "no"
  >
  <!ELEMENT relationship EMPTY>
  <!ATTLIST relationship
      name CDATA #REQUIRED
      description CDATA ""
      class-type CDATA #REQUIRED
      low-cc (zero|one) #REQUIRED
      high-cc (one|many) #REQUIRED
      is-composite (yes|no) #REQUIRED
      is-exclusive (yes|no) #REQUIRED
      is-dependent (yes|no) #REQUIRED
      ordered (yes|no) "no"
  >
  <!ELEMENT method (method-implementation*)>
  <!ATTLIST method
      name CDATA #REQUIRED
      description CDATA ""
  >
  <!ELEMENT method-implementation EMPTY>
  <!ATTLIST method-implementation
      language CDATA #REQUIRED
      prototype CDATA #REQUIRED
      body CDATA ""
  >
]>

<oks-schema>

<info name="" type="" num-of-items="1" oks-format="schema" oks-version="oks-08-03-03 built &quot;May  3 2021&quot;" created-by="nswdaq" created-on="pcatlnswswrodvs.cern.ch" creation-time="20211104T131927" last-modified-by="nswdaq" last-modified-on="pcatlnswswrodvs.cern.ch" last-modification-time="20211115T093256"/>

<include>
 <file path="is/is.xml"/>
</include>

 <class name="Statistics" description="Statistics for monitoring group">
  <superclass name="Info"/>
  <attribute name="time" description="Time used by monitoring in ms" type="u64" format="dec" init-value="0"/>
 </class>

 <class name="RocStatus">
  <superclass name="Info"/>
  <attribute name="captureStatusVmm" description="Capture status of VMM0-7" type="u8" format="hex" is-multi-value="yes" init-value="0"/>
  <attribute name="parityCounterVmm" description="Parity error counter of VMM0-7" type="u8" format="hex" is-multi-value="yes" init-value="0"/>
  <attribute name="statusSroc" description="Status of sROC0-4" type="u8" format="hex" is-multi-value="yes" init-value="0"/>
  <attribute name="seu" description="Single event upset flag" type="u8" format="hex" init-value="0"/>
  <attribute name="seuCounter" description="SEU pulses counter" type="u8" format="hex" init-value="0"/>
 </class>

 <class name="RocConfiguration">
  <superclass name="Info"/>
  <attribute name="reg115" description="reg115" type="u8" format="hex" init-value="0"/>
 </class>

 <class name="PadTriggerRegisters">
  <superclass name="Info"/>
  <attribute name="conf_bcid_offset" description="BCID offset" type="u32" format="hex" init-value="0"/>
  <attribute name="conf_ro_bc_offset" description="Readout BC offset" type="u32" format="hex" init-value="0"/>
  <attribute name="trigger_rate" description="Coincidence trigger rate" type="u32" init-value="0"/>
  <attribute name="xadc_temp" description="xADC FPGA temperature" type="u32" init-value="0"/>
  <attribute name="pfeb_bcids" description="PFEB BCID" type="u32" is-multi-value="yes"/>
  <attribute name="pfeb_status" description="PFEB status" type="u32" format="hex" init-value="0"/>
  <attribute name="pad_bcid_error" description="Pad BCID error" type="u32" init-value="0"/>
  <attribute name="pad_bcid_error_dif" description="Pad BCID error diff" type="u32" init-value="0"/>
  <attribute name="pt_2_tp_lat" description="PT-2-TP latency" type="u32" init-value="0"/>
  <attribute name="tp_bcid_error" description="TP BCID error" type="u32" init-value="0"/>
  <attribute name="tp_bcid_error_dif" description="TP BCID error diff" type="u32" init-value="0"/>
  <attribute name="ttc_bcr_ocr_rate" description="TTC BCR/OCR rate" type="u32" init-value="0"/>
 </class>

 <class name="MmtpInRunStatusRegisters">
  <superclass name="Info"/>
  <attribute name="artFibersAlignment" description="32 fiber alignment status" type="bool" is-multi-value="yes"/>
  <attribute name="artFibersBcidGood" description="32 fiber bcid the same as MMTP" type="bool" is-multi-value="yes"/>

  <attribute name="idleState" description="Idle State Indicator" type="bool"/>
  <attribute name="bcidOffset" description="BCID offset for BCID counter in Global Sync Module" type="u32"/>
  <attribute name="suggestedBcidOffset" description="suggested BCID offset based on input ADDC BCID" type="u32"/>
  <attribute name="nGoodOffset" description="number of ADDC that satisfies BCID offset" type="u32"/>
  <attribute name="fiberBCIDs" description="Real time 4-bit LSB of BCID of each ART fiber" type="u8" is-multi-value="yes"/>
 </class>

 <class name="MmtpOutRunStatusRegisters">
  <superclass name="Info"/>
  <attribute name="txMicropodTemp" description="Temperature of 3 TX micropods, indexed in MTP order" type="float" is-multi-value="yes"/>
  <attribute name="rxMicropodTemp" description="Temperature of 3 RX micropods, indexed in MTP order" type="float" is-multi-value="yes"/>
  <attribute name="txLoss" description="Loss of 36 TX fibers" type="bool" is-multi-value="yes"/>
  <attribute name="rxLoss" description="Loss of 36 RX fiber" type="bool" is-multi-value="yes"/>
  <attribute name="txFibersPower" description="36 TX fiber power reading" type="float" is-multi-value="yes"/>
  <attribute name="rxArtFibersPower" description="32 RX fiber power reading in uW (4 unconnected channel should read 0)" type="float" is-multi-value="yes"/>
 </class>

 <class name="StgctpInRunStatusRegisters">
  <superclass name="Info"/>
 </class>

 <class name="StgctpOutRunStatusRegisters">
  <superclass name="Info"/>
 </class>

</oks-schema>
